---
# https://goreleaser.com/customization/project/
project_name: amazon-ssm-agent

variables:
  Vendor: amazon-ssm-agent authors
  VendorHomepage: https://aws.amazon.com/systems-manager/
  License: Apache-2.0
  Description: |-
    An agent to enable remote management of your EC2 instances, on-premises
    servers, or virtual machines (VMs).

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
