---
# https://goreleaser.com/customization/project/
project_name: fzf

variables:
  Vendor: fzf authors
  VendorHomepage: https://github.com/junegunn/fzf
  License: MIT
  Description: |-
    A command-line fuzzy finder.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
