---
# https://goreleaser.com/customization/project/
project_name: git-cliff

variables:
  Vendor: git-cliff authors
  VendorHomepage: https://git-cliff.org
  License: Apache-2.0, MIT
  Description: |-
    A highly customizable Changelog Generator that follows Conventional Commit
    specifications.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_nightly.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .

# https://goreleaser.com/customization/builds/#import-pre-built-binaries
builds:
  - id: prebuilt-glibc
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: "/usr/local/bin/{{ .ProjectName }}_{{ .Arch }}"
    binary: "{{ .ProjectName }}"

  - id: prebuilt-musl
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: "/usr/local/bin/{{ .ProjectName }}_musl_{{ .Arch }}"
    binary: "{{ .ProjectName }}"

# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: package-glibc
    builds:
      - prebuilt-glibc
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "{{ .Var.Vendor }}"
    homepage: "{{ .Var.VendorHomepage }}"
    maintainer: Northwood Labs <packages@northwood-labs.com>
    description: "{{ .Var.Description }}"
    license: "{{ .Var.License }}"
    formats:
      - deb
      - rpm
    umask: 0o002
    release: 1
    rpm:
      summary: "{{ .Var.Description }}"
      packager: Northwood Labs <packages@northwood-labs.com>
      compression: lzma
      # signature:
      #   key_file: "{{ .Env.GPG_KEY_PATH }}"
    deb:
      # signature:
      #   key_file: "{{ .Env.GPG_KEY_PATH }}"
      #   type: origin

  - id: package-musl
    builds:
      - prebuilt-musl
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "{{ .Var.Vendor }}"
    homepage: "{{ .Var.VendorHomepage }}"
    maintainer: Northwood Labs <packages@northwood-labs.com>
    description: "{{ .Var.Description }}"
    license: "{{ .Var.License }}"
    formats:
      - apk
    umask: 0o002
    release: 1
    apk:
      # signature:
      #   key_file: "{{ .Env.GPG_KEY_PATH }}"
      #   key_name: origin
