---
# https://goreleaser.com/customization/project/
project_name: yamlfmt

variables:
  Vendor: yamlfmt authors
  VendorHomepage: https://github.com/google/yamlfmt
  License: MIT
  Description: |
    An extensible command line tool or library to format YAML files.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
