---
# https://goreleaser.com/customization/project/
project_name: yamlfmt

variables:
  Vendor: yamlfmt authors
  VendorHomepage: https://github.com/google/yamlfmt
  License: MIT
  Description: |
    An extensible command line tool or library to format YAML files.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
