---
# https://goreleaser.com/customization/project/
project_name: lychee

variables:
  Vendor: lychee authors
  VendorHomepage: https://eza.rocks
  License: MIT
  Description: |-
    Fast, async, stream-based link checker written in Rust. Finds broken URLs
    and mail addresses inside Markdown, HTML, reStructuredText, websites and
    more!

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds_glibc.yml
  - from_file:
      path: ../_builds_musl_amd64.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms_glibc.yml
  - from_file:
      path: ../_nfpms_musl_amd64.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
