---
# https://goreleaser.com/customization/project/
project_name: direnv

variables:
  Vendor: direnv authors
  VendorHomepage: http://direnv.net
  License: MIT
  Description: |-
    Unclutter your .profile.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
