---
# https://goreleaser.com/customization/project/
project_name: infracost

variables:
  Vendor: Infracost
  VendorHomepage: https://infracost.io
  License: Apache-2.0
  Description: |
    Cloud cost estimates for Terraform in pull requests💰📉 Shift FinOps Left!

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
