---
# https://goreleaser.com/customization/project/
project_name: goplicate

variables:
  Vendor: goplicate authors
  VendorHomepage: https://github.com/ilaif/goplicate
  License: MIT
  Description: |-
    A CLI tool that helps define common code or configuration snippets once, and
    sync it to multiple projects.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
