---
# https://goreleaser.com/customization/project/
project_name: docker-buildx

variables:
  Vendor: docker-buildx authors
  VendorHomepage: https://docs.docker.com/build/buildkit/
  License: Apache-2.0
  Description: |
    Docker CLI plugin for extended build capabilities with BuildKit.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_nightly.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .

# https://goreleaser.com/customization/builds/#import-pre-built-binaries
builds:
  - id: prebuilt
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: "/usr/local/bin/buildx_{{ .Arch }}"
    binary: "buildx"

# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: package
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - prebuilt
    vendor: "{{ .Var.Vendor }}"
    homepage: "{{ .Var.VendorHomepage }}"
    maintainer: Northwood Labs <packages@northwood-labs.com>
    description: "{{ .Var.Description }}"
    license: "{{ .Var.License }}"
    formats:
      - apk
      - deb
      - rpm
    umask: 0o002
    release: 1
    bindir: /usr/local/lib/docker/cli-plugins
    rpm:
      summary: "{{ .Var.Description }}"
      packager: Northwood Labs <packages@northwood-labs.com>
      compression: lzma
      signature:
        key_file: 3C7658F0.asc
    deb:
      signature:
        key_file: 3C7658F0.asc
        type: archive
    apk:
      signature:
        key_file: signing.pem
        key_name: "signing-keys@northwood-labs.com"
