---
# https://goreleaser.com/customization/project/
project_name: driftwood

variables:
  Vendor: Truffle Security
  VendorHomepage: https://github.com/trufflesecurity/driftwood
  License: Apache-2.0
  Description: |-
    Private key usage verification.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
