---
# https://goreleaser.com/customization/project/
project_name: pandoc3

variables:
  Vendor: pandoc authors
  VendorHomepage: https://pandoc.org
  License: GPL-2.0
  Description: |
    Universal markup converter.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .

# https://goreleaser.com/customization/builds/#import-pre-built-binaries
builds:
  - id: prebuilt
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: "/usr/local/bin/{{ .ProjectName }}_{{ .Arch }}"
    binary: "pandoc"
