---
# https://goreleaser.com/customization/project/
project_name: editorconfig-checker

variables:
  Vendor: editorconfig-checker authors
  VendorHomepage: https://editorconfig-checker.github.io
  License: MIT
  Description: |-
    A tool to verify that your files are in harmony with your .editorconfig.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
