---
# https://goreleaser.com/customization/project/
project_name: trivy

variables:
  Vendor: Aqua Security
  VendorHomepage: https://aquasecurity.github.io/trivy
  License: Apache-2.0
  Description: |-
    Find vulnerabilities, misconfigurations, secrets, SBOM in containers,
    Kubernetes, code repositories, clouds and more.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
