---
# https://goreleaser.com/customization/project/
project_name: cosign

variables:
  Vendor: cosign authors
  VendorHomepage: https://github.com/sigstore/cosign
  License: Apache-2.0
  Description: |-
    Code signing and transparency for containers and binaries.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
