---
# https://goreleaser.com/customization/project/
project_name: gocovsh

variables:
  Vendor: gocovsh authors
  VendorHomepage: https://github.com/orlangure/gocovsh
  License: GPL-3.0
  Description: |-
    Go Coverage in your terminal: a tool for exploring Go Coverage reports from
    the command line.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
