---
# https://goreleaser.com/customization/project/
project_name: hugo

variables:
  Vendor: hugo authors
  VendorHomepage: https://gohugo.io
  License: Apache-2.0
  Description: |
    The world's fastest framework for building websites.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
