---
# https://goreleaser.com/customization/project/
project_name: gommit

variables:
  Vendor: gommit authors
  VendorHomepage: https://github.com/antham/gommit
  License: Apache-2.0
  Description: |
    Enforce git message commit consistency.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
