---
# https://goreleaser.com/customization/project/
project_name: iamlive

variables:
  Vendor: iamlive authors
  VendorHomepage: https://github.com/iann0036/iamlive
  License: MIT
  Description: |-
    Generate an IAM policy from AWS, Azure, or Google Cloud (GCP) calls using
    client-side monitoring (CSM) or embedded proxy.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
