---
# https://goreleaser.com/customization/project/
project_name: trufflehog

variables:
  Vendor: Truffle Security
  VendorHomepage: https://trufflesecurity.com
  License: AGPL-3.0
  Description: |-
    An open-source secret scanning engine that detects and helps resolve exposed
    secrets across your entire tech stack.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
