---
# https://goreleaser.com/customization/project/
project_name: cloud-nuke

variables:
  Vendor: Gruntwork
  VendorHomepage: https://github.com/gruntwork-io/cloud-nuke
  License: MIT
  Description: |-
    A tool for cleaning up your cloud accounts by nuking (deleting) all
    resources within it.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
