---
# https://goreleaser.com/customization/project/
project_name: chamber

variables:
  Vendor: Segment
  VendorHomepage: https://github.com/segmentio/chamber
  License: MIT
  Description: |-
    CLI for managing secrets via AWS Parameter Store.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
