---
# https://goreleaser.com/customization/project/
project_name: gama

variables:
  Vendor: gama authors
  VendorHomepage: https://github.com/termkit/gama
  License: GPL-3.0
  Description: |
    Manage your GitHub Actions from Terminal with great UI.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
