---
# https://goreleaser.com/customization/project/
project_name: eza

variables:
  Vendor: eza authors
  VendorHomepage: https://eza.rocks
  License: MIT
  Description: |-
    A modern, maintained replacement for ls.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds_glibc.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms_glibc.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
