---
# https://goreleaser.com/customization/project/
project_name: goreleaser-pro

variables:
  Vendor: goreleaser authors
  VendorHomepage: https://goreleaser.com/pro
  License: Proprietary
  Description: |-
    Deliver Go binaries as fast and easily as possible. (Pro version)

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .

# https://goreleaser.com/customization/builds/#import-pre-built-binaries
builds:
  - id: prebuilt
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: "/usr/local/bin/{{ .ProjectName }}_{{ .Arch }}"
    binary: "goreleaser"
