---
# https://goreleaser.com/customization/project/
project_name: goreleaser-pro

variables:
  Vendor: goreleaser authors
  VendorHomepage: https://goreleaser.com/pro
  License: Proprietary
  Description: |-
    Deliver Go binaries as fast and easily as possible. (Pro version)

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
