---
# https://goreleaser.com/customization/project/
project_name: govulncheck

variables:
  Vendor: govulncheck authors
  VendorHomepage: https://github.com/golang/vuln
  License: BSD-3-Clause
  Description: |
    The database client and tools for the Go vulnerability database.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
