---
# https://goreleaser.com/customization/project/
project_name: gum

variables:
  Vendor: gum authors
  VendorHomepage: https://github.com/charmbracelet/gum
  License: MIT
  Description: |
    A tool for glamorous shell scripts.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
