---
# https://goreleaser.com/customization/project/
project_name: tenv

variables:
  Vendor: tenv authors
  VendorHomepage: https://tofuutils.github.io/tenv/
  License: Apache-2.0
  Description: |
    A versatile version manager for OpenTofu, Terraform, and Terragrunt.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
