---
# https://goreleaser.com/customization/project/
project_name: tenv

variables:
  Vendor: tenv authors
  VendorHomepage: https://tofuutils.github.io/tenv/
  License: Apache-2.0
  Description: |
    A versatile version manager for OpenTofu, Terraform, and Terragrunt.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .

# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: package
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - prebuilt
    vendor: "{{ .Var.Vendor }}"
    homepage: "{{ .Var.VendorHomepage }}"
    maintainer: Northwood Labs <packages@northwood-labs.com>
    description: "{{ .Var.Description }}"
    license: "{{ .Var.License }}"
    formats:
      - apk
      - deb
      - rpm
    umask: 0o002
    release: 1
    bindir: /usr/local/bin
    contents:
      - src: /usr/local/bin/tenv_{{.Arch}}
        dst: /usr/local/bin/tenv
        file_info:
          mode: 0755
      - src: /usr/local/bin/terraform_{{.Arch}}
        dst: /usr/local/bin/terraform
        file_info:
          mode: 0755
      - src: /usr/local/bin/terragrunt_{{.Arch}}
        dst: /usr/local/bin/terragrunt
        file_info:
          mode: 0755
      - src: /usr/local/bin/tf_{{.Arch}}
        dst: /usr/local/bin/tf
        file_info:
          mode: 0755
      - src: /usr/local/bin/tofu_{{.Arch}}
        dst: /usr/local/bin/tofu
        file_info:
          mode: 0755
    rpm:
      summary: "{{ .Var.Description }}"
      packager: Northwood Labs <packages@northwood-labs.com>
      compression: lzma
      signature:
        key_file: 3C7658F0.asc
    deb:
      signature:
        key_file: 3C7658F0.asc
        type: archive
    apk:
      signature:
        key_file: signing.pem
        key_name: "signing-keys@northwood-labs.com"
