---
# https://goreleaser.com/customization/project/
project_name: svu

variables:
  Vendor: svu authors
  VendorHomepage: https://github.com/caarlos0/svu
  License: MIT
  Description: |
    Semantic version utilities.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
