---
# https://goreleaser.com/customization/project/
project_name: tomljson

variables:
  Vendor: tomljson authors
  VendorHomepage: https://github.com/pelletier/go-toml
  License: MIT
  Description: |
    A program that converts TOML to JSON.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
