---
# https://goreleaser.com/customization/project/
project_name: hadolint

variables:
  Vendor: hadolint authors
  VendorHomepage: https://github.com/hadolint/hadolint
  License: GPL-3.0
  Description: |
    Dockerfile linter, validate inline bash, written in Haskell.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
