---
# https://goreleaser.com/customization/project/
project_name: nfpm

variables:
  Vendor: nfpm authors
  VendorHomepage: https://nfpm.goreleaser.com
  License: MIT
  Description: |
    nFPM is Not FPM - a simple deb, rpm, apk and arch linux packager written in Go.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../shared.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
