---
# https://goreleaser.com/customization/project/
project_name: unconvert

variables:
  Vendor: unconvert authors
  VendorHomepage: https://github.com/mdempsky/unconvert
  License: BSD-3-Clause
  Description: |
    Remove unnecessary type conversions from Go source.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
