---
# https://goreleaser.com/customization/project/
project_name: diffoci

variables:
  Vendor: diffoci authors
  VendorHomepage: https://github.com/reproducible-containers/diffoci
  License: Apache-2.0
  Description: |-
    Diff for Docker and OCI container images.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
