---
# https://goreleaser.com/customization/project/
project_name: aws-session-manager-plugin

variables:
  Vendor: aws-session-manager-plugin authors
  VendorHomepage: https://github.com/aws/session-manager-plugin
  License: Apache-2.0
  Description: |-
    This plugin helps you to use the AWS Command Line Interface (AWS CLI) to
    start and end sessions to your managed instances.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
