---
# https://goreleaser.com/customization/project/
project_name: aws-vault

variables:
  Vendor: aws-vault authors
  VendorHomepage: https://github.com/99designs/aws-vault
  License: MIT
  Description: |-
    A vault for securely storing and accessing AWS credentials in development
    environments.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
