---
# https://goreleaser.com/customization/project/
project_name: lefthook

variables:
  Vendor: Evil Martians
  VendorHomepage: https://github.com/evilmartians/lefthook
  License: MIT
  Description: |
    Fast and powerful Git hooks manager for any type of projects.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
