---
# https://goreleaser.com/customization/project/
project_name: smrcptr

variables:
  Vendor: smrcptr authors
  VendorHomepage: https://github.com/nikolaydubina/smrcptr
  License: MIT
  Description: |
    Detect mixing pointer and value method receivers.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
