---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "🎯 Step: Build and cache (go build)"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version:
        required: true
        type: string
      clone-repository:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-and-cache
  cancel-in-progress: true

# Variables available to all jobs defined in this file
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ${{ vars.REGISTRY }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  generate:
    runs-on: ubuntu-latest
    name: "📦 Build and cache (go build)"
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/northwood-labs/package-builder/ubuntu-v22.04:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged

    steps:
      - name: Git clone
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.base_ref }}

      - name: Restore any cached build artifacts (musl-aarch64)
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: restore-musl-aarch64
        with:
          key: "build-cache-${{ inputs.package-name }}-${{ inputs.package-version }}-musl-aarch64"
          path: "/usr/bin/${{ inputs.package-name }}_musl_arm64"

      - name: Restore any cached build artifacts (musl-x86_64)
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: restore-musl-x86_64
        with:
          key: "build-cache-${{ inputs.package-name }}-${{ inputs.package-version }}-musl-x86_64"
          path: "/usr/bin/${{ inputs.package-name }}_musl_amd64"

      - name: "📦 Build the package"
        working-directory: packages/${{ inputs.package-name }}
        env:
          CLONE_REPO: "${{ inputs.clone-repository }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
          GPG_KEY_B64: ${{ secrets.GPG_KEY_B64 }}
          NFPM_PASSPHRASE: "${{ secrets.GPG_PWD }}"
          PKG_VER: "${{ inputs.package-version }}"
          RSA_KEY_B64: ${{ secrets.RSA_KEY_B64 }}
        run: |
          # We just need to set a git tag. None of the rest of this matters.
          git init
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git add .
          git commit -m "Test"
          git remote add origin https://example.com
          git tag "${{ inputs.package-version }}"

          # Decode the contents into files.
          echo -n "${GPG_KEY_B64}" | base64 --decode > 3C7658F0.asc
          echo -n "${RSA_KEY_B64}" | base64 --decode > signing.pem

          # Build the package
          goreleaser release --clean --nightly --skip=announce,publish,validate --verbose

      - name: Cache the packages
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: cache-packages
        with:
          key: "${{ inputs.package-name }}-${{ inputs.package-version }}"
          path: packages/${{ inputs.package-name }}/dist
