---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "🎯 Step: Build and cache (nFPM)"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-and-cache-nfpm
  cancel-in-progress: true

# Variables available to all jobs defined in this file
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ${{ vars.REGISTRY }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  generate:
    runs-on: ubuntu-latest
    name: "📦 Build and cache (nFPM)"
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/northwood-labs/package-builder/ubuntu-v22.04:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Git clone
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.base_ref }}

      - name: "📦 Build the package (nFPM)"
        working-directory: packages/${{ inputs.package-name }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GPG_KEY_B64: ${{ secrets.GPG_KEY_B64 }}
          NFPM_PASSPHRASE: "${{ secrets.GPG_PWD }}"
          PKG_VER: "${{ inputs.package-version }}"
          RSA_KEY_B64: ${{ secrets.RSA_KEY_B64 }}
        run: |
          # Decode the contents into files.
          echo -n "${GPG_KEY_B64}" | base64 --decode > 3C7658F0.asc
          echo -n "${RSA_KEY_B64}" | base64 --decode > signing.pem

          bash ./download.sh

          # Build the package
          mkdir -p ./dist
          nfpm package --packager apk --target ./dist
          nfpm package --packager deb --target ./dist
          nfpm package --packager rpm --target ./dist

      - name: Cache the packages
        uses: actions/cache/save@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        id: cache-packages
        with:
          key: "${{ inputs.package-name }}-${{ inputs.package-version }}"
          path: packages/${{ inputs.package-name }}/dist
