---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "🎯 Step: Build packages for musl"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-and-cache
  cancel-in-progress: true

# Variables available to all jobs defined in this file
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ${{ vars.REGISTRY }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  # https://github.com/orgs/community/discussions/38728
  compile:
    runs-on: ubuntu-latest
    name: "musl-${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.base_ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: ${{ matrix.arch }}

      - name: Run in Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run \
            --rm \
            --env GITHUB_TOKEN \
            --volume "$PWD:/${{ github.workspace }}" \
            --workdir ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ghcr.io/northwood-labs/package-builder/alpine-v3.19:latest \
            bash packages/${{ inputs.package-name }}/compile-alpine-${{ matrix.arch }}.sh "${{ inputs.package-version }}"

            cp -vf "${{ github.workspace }}/builds/usr/bin/${{ inputs.package-name }}_musl_${{ matrix.arch }}" /usr/local/bin/${{ inputs.package-name }}_musl_${{ matrix.arch }}

      - name: Cache the packages
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-packages
        with:
          key: "build-cache-${{ inputs.package-name }}-${{ inputs.package-version }}-musl-${{ matrix.arch }}"
          path: "/usr/local/bin/${{ inputs.package-name }}_musl_${{ matrix.arch }}"
