---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "🎯 Step: Build and cache (prebuilt)"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-and-cache-prebuilt
  cancel-in-progress: true

# Variables available to all jobs defined in this file
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ${{ vars.REGISTRY }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  generate:
    runs-on: ubuntu-latest
    name: "📦 Build and cache (prebuilt)"
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/northwood-labs/package-builder/ubuntu-v22.04:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Git clone
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.base_ref }}

      - name: "📦 Build the package"
        working-directory: packages/${{ inputs.package-name }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PKG_VER: "${{ inputs.package-version }}"
          PKG_NAME: "${{ inputs.package-name }}"
        run: |
          # We're pulling already-built packages.
          bash ./download.sh

      - name: Cache the packages
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: cache-packages
        with:
          key: "${{ inputs.package-name }}-${{ inputs.package-version }}"
          path: packages/${{ inputs.package-name }}/dist
