---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "Step: Build packages for musl-aarch64"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-and-cache
  cancel-in-progress: true

# Variables available to all jobs defined in this file
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ${{ vars.REGISTRY }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  # https://github.com/orgs/community/discussions/38728
  compile:
    runs-on: ubuntu-latest
    name: Compile musl-aarch64
    strategy:
      fail-fast: false
      matrix:
        arch:
          # - docker: amd64 # used by docker create --platform
          - docker: arm64

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}

      - name: Run in Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run \
            --rm \
            --env GITHUB_TOKEN \
            --volume "$PWD:/${{ github.workspace }}" \
            --workdir ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ghcr.io/northwood-labs/package-builder/alpine-v3.19:latest \
            bash packages/${{ inputs.package-name }}/compile-alpine-arm64.sh "${{ inputs.package-version }}"

            cp -vf "${{ github.workspace }}/builds/usr/bin/${{ inputs.package-name }}_musl_arm64" /usr/bin/${{ inputs.package-name }}_musl_arm64

      - name: Cache the packages
        uses: actions/cache/save@v4
        id: cache-packages
        with:
          key: "build-cache-${{ inputs.package-name }}-${{ inputs.package-version }}-musl-aarch64"
          path: "/usr/bin/${{ inputs.package-name }}_musl_arm64"
