---
# https://goreleaser.com/customization/project/
project_name: dive

variables:
  Vendor: dive authors
  VendorHomepage: https://github.com/wagoodman/dive
  License: MIT
  Description: |-
    A tool for exploring each layer in a Docker image.

# https://goreleaser.com/customization/includes/
includes:
  - from_file:
      path: ../_dist.yml
  - from_file:
      path: ../_env.yml
  - from_file:
      path: ../_builds.yml
  - from_file:
      path: ../_nightly.yml
  - from_file:
      path: ../_nfpms.yml

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - cmd: |
        bash ./download.sh
      output: true
      dir: .
